### ISSUE TITLE
Tomcat

### ISSUE THREAD

**Issue by masterdany88** [errai/errai-tutorial#6]
Hey. How I can run this demo project on tomcat in eclipse?
When I start tomcat I am getting an error:
```
Caused by: java.lang.IllegalArgumentException: Servlet mapping specifies an unknown servlet name javax.ws.rs.core.Application
	at org.apache.catalina.core.StandardContext.addServletMappingDecoded(StandardContext.java:3126)
	at org.apache.catalina.Context.addServletMappingDecoded(Context.java:879)
	at org.apache.catalina.startup.ContextConfig.configureContext(ContextConfig.java:1376)
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1190)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:775)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5077)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
```
Or on Jetty:
```
WARN [AbstractLifeCycle] FAILED org.eclipse.jetty.server.session.SessionHandler@4ad22f81: java.lang.IllegalStateException: No such servlet: javax.ws.rs.core.Application
java.lang.IllegalStateException: No such servlet: javax.ws.rs.core.Application
```

**Comment by mbarkley** [comment]
That missing servlet is the JAX-RS servlet. Most of the Errai demos are designed to be deployed to JavaEE servers, so they do not include JAX-RS jars in their war files. If you are deploying to Tomcat, you will need to bundle those jars into your war.
